Repository HackGT/registration, pull requests merged in 2018-03, with the labels that each got.

#201 Metrics Event Updates
  package-lock.json
  package.json
  server/routes/api/user.ts
Labels: enhancement, medium priority

#189 Fix morgan status code coloring bug
  server/app.ts
Labels: bug, low priority

#204 Implement custom email subjects
  LICENSE
  README.md
  client/admin.html
  client/js/admin.ts
  package-lock.json
  package.json
  server/common.ts
  server/routes/api/settings.ts
  server/routes/api/user.ts
Labels: enhancement, high priority
