Repository HackGT/registration, pull requests merged in 2018-10, with the labels that each got.

#243 Tweak wording in client
  client/admin.html
  client/index.html
  package-lock.json
  package.json
Labels: bug, low priority

#246 Add templating for uuid QRCode data URL
  client/admin.html
  package-lock.json
  package.json
  server/common.ts
  server/tsconfig.json
Labels: enhancement, medium priority

#247 Support non authed linking
  package-lock.json
  package.json
  server/middleware.ts
  server/routes/strategies.ts
  server/routes/templates.ts
Labels: enhancement, medium priority

#248 Add admin status to the user info endpoint
  server/routes/api/user.ts
Labels: enhancement, low priority
