Repository HackGT/registration, pull requests merged in 2019-08, with the labels that each got.

#278 Add an asychronous email queue for registration
  cloudbuild.yaml
  package-lock.json
  package.json
  server/common.ts
  server/routes/api/settings.ts
  server/routes/api/user.ts
Labels: bug, high priority

#279 Consolidate API requests authed with bearer to a single function call
  package-lock.json
  package.json
  server/routes/auth.ts
  server/routes/strategies.ts
Labels: bug, medium priority

#280 Logic to close travel reimbursements for HackGT 6
  client/index.html
  server/common.ts
  server/config/questions.json
  server/routes/templates.ts
  server/schema.ts
Labels: enhancement, high priority
