Repository HackGT/registration, pull requests merged in 2019-03, with the labels that each got.

#256 Only use local registration by default to ease developer setup
  server/common.ts
Labels: enhancement, low priority

#257 Re-setting the same status shouldn't wipe user confirmation
  package.json
  server/routes/api/user.ts
Labels: bug, medium priority

#261 Force users to choose an option for <select> dropdowns
  client/application.html
  client/confirmation.html
  client/login.html
  client/partials/form.html
  package-lock.json
  package.json
  server/config/questions.json
  server/routes/api/user.ts
  server/routes/templates.ts
  server/schema.ts
Labels: bug, medium priority, pending review

#263 Fixes for stat graphs in admin panel
  client/admin.html
  client/js/admin.ts
  package-lock.json
  package.json
  server/common.ts
  server/routes/templates.ts
  server/schema.ts
Labels: bug, medium priority
